### PR TITLE
Missing lib libhidapi-dev for USB pendant

### PR DESCRIPTION
**Pull request by alkabal**

### CODE REVIEW

**Comment by wolfmanjm** [comment]
This is not needed unless you use a HID pendant and that is why it is NOT specified for normal installations. I think it is mentioned in the Pendant section.

**Comment by wolfmanjm** [comment]
Sorry misread it. I did not need this on my RPI....  

> p   libhidapi-dev                           - Multi-Platform library for communication with HID

It is not installed on my pi that has my pendant on it.

**Comment by alkabal** [comment]
I have use your last image v2 for generate a bootable usb key and the pendant does work without this (tested also with hb04)

Br

**Comment by alkabal** [comment]
[WARNING] [load_modules] exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/easyhid-0.0.10-py3.5.egg/easyhid/easyhid.py", line 63, in <module>
    hidapi = ffi.dlopen('hidapi-hidraw')
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'hidapi-hidraw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1332, in _load_modules
    mod = importlib.import_module('modules.{}'.format(key))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/smoopi/modules/whb04b.py", line 14, in <module>
    from easyhid import Enumeration
  File "/usr/local/lib/python3.5/dist-packages/easyhid-0.0.10-py3.5.egg/easyhid/__init__.py", line 8, in <module>
    from easyhid.easyhid import *
  File "/usr/local/lib/python3.5/dist-packages/easyhid-0.0.10-py3.5.egg/easyhid/easyhid.py", line 72, in <module>
    hidapi = ffi.dlopen(libname)
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.5/dist-packages/cffi-1.14.0-py3.5-linux-armv7l.egg/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libhidapi-hidraw.so.0': libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libhidapi-hidraw.so.0'

**Comment by alkabal** [comment]
also at boot i have this error :

failed to start /etc/rc.local compatibility

**Comment by wolfmanjm** [comment]
ok tested it out it actually needs libhidapi-hidraw0 not the dev version.

Thanks for pointing this out to me.

**Comment by wolfmanjm** [comment]
odd thing is this is only required on one of my systems, not the other, the one with the raw hid runs without it. On my other it was needed. very odd.

**Comment by alkabal** [comment]
I does not have this lib with my old sdcard image but required with new one, and sorry you are right i have first installed the dev version taht automatically install hidraw0.

**Comment by wolfmanjm** [comment]
The images are the same thing. I just did an apt upgrade. So not sure why it made any difference, the OS is the same.

**Comment by alkabal** [comment]
Can i ask itt is now possible to use network or it is same as before not fully usable ?

**Comment by wolfmanjm** [comment]
Network on V1 smoothie has never been usable. It was just a test, it is not for production. Only USB is optimized for use. Smoopi does allow connection to a network device but it is not recommended and is not supported.

**Comment by alkabal** [comment]
Ok thanks !

Also i have see the missing gcode directory in home. (viewer open in gcode directory but if you click on ../ you see the folder is not here.

**Comment by alkabal** [comment]
i suspect newer release of python-easyhid need this new dependancy

**Pull request closed without merging**
